server:
  name: "notary-server"
  host: "0.0.0.0"
  port: 7047

notarization:
  max-transcript-size: 16384

tls:
  enabled: true
  private-key-pem-path: "./fixture/tls/notary.key"
  certificate-pem-path: "./fixture/tls/notary.crt"

notary-key:
  signing-key-type-name: "mina-schnorr"
  private-key-pem-path: "./fixture/schnorr/notary.key"
  public-key-pem-path: "./fixture/schnorr/notary.pub"

logging:
  level: DEBUG

authorization:
  enabled: false
  whitelist-csv-path: "./fixture/auth/whitelist.csv"
